In [90]:
import numpy as np
import keras
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [91]:
x_train = x_train.reshape((-1, 784))
print(x_train.shape)

(60000, 784)


In [92]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
temp_y_train = y_train.reshape(-1, 1)
temp_y_test = y_test.reshape(-1, 1)
temp_y_train = enc.fit_transform(temp_y_train).toarray()
temp_y_test = enc.transform(temp_y_test).toarray()

In [93]:
print(temp_y_train[1])

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [94]:
from keras import Sequential
from keras.layers import Dense, Dropout

model = Sequential()

In [95]:
model.add(Dense(128, activation = "gelu"))
model.add(Dropout(0.1))
model.add(Dense(64, activation = "gelu"))
model.add(Dropout(0.1))
model.add(Dense(32, activation = "gelu"))
model.add(Dropout(0.1))
model.add(Dense(10, activation = "softmax"))

In [96]:
model.compile(optimizer = "adam", loss = "categorical_crossentropy", metrics = ["accuracy"])

In [97]:
from sklearn.model_selection import train_test_split

x_train, x_clf, temp_y_train, y_clf = train_test_split(x_train, temp_y_train, test_size = 0.3)

In [98]:
print(temp_y_train.shape)
print(x_train.shape)

(42000, 10)
(42000, 784)


In [99]:
model.fit(x_train, temp_y_train, epochs = 50, batch_size = 512)

Epoch 1/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.2366 - loss: 19.8327
Epoch 2/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4108 - loss: 1.9372
Epoch 3/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6001 - loss: 1.3771
Epoch 4/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7199 - loss: 1.0585
Epoch 5/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7610 - loss: 0.8724
Epoch 6/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.7193
Epoch 7/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8177 - loss: 0.6447
Epoch 8/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8464 - loss: 0.5502
Epoch 9/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8666 - loss: 0.4948
Epoch 10/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8728 - loss: 0.4485
Epoch 11/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8925 - loss: 0.3910
Epoch 12/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8949 - l

In [100]:
clf_predict = model.predict(x_clf)

563/563 ━━━━━━━━━━━━━━━━━━━━ 1s 950us/step


In [101]:
res = []
for row in clf_predict:
    ind = np.argmax(row)
    res.append(ind)
res = np.array(res)
print(res.shape)

(18000,)


In [102]:
res_clf = []
for row in y_clf:
    ind = np.argmax(row)
    res_clf.append(ind)
res_clf = np.array(res_clf)
print(res_clf.shape)

(18000,)


In [107]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(res_clf, res), accuracy_score(res_clf, res)

(array([[1691,    0,    5,    1,    1,    3,   10,    0,   12,    4],
        [   2, 1941,   14,   12,    5,    0,    3,    3,    9,    6],
        [  10,    5, 1691,   25,    5,    2,    7,   23,   21,    2],
        [   0,    2,   12, 1761,    1,   12,    1,   13,   16,   10],
        [   4,    2,    8,    2, 1730,    0,   10,    1,    5,   18],
        [   4,    3,    1,   40,    2, 1563,   27,    4,   11,    6],
        [   8,    4,    0,    0,    5,   12, 1795,    0,   10,    0],
        [   0,    8,   13,    8,    5,    1,    1, 1790,    1,    6],
        [   6,    8,    9,   35,    7,    9,    8,    8, 1688,   10],
        [   7,    4,    2,   23,   44,    4,    1,   33,   13, 1632]],
       dtype=int64),
 0.9601111111111111)

In [105]:
x_test = x_test.reshape(-1, 784)
y_pred = model.predict(x_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step


In [106]:
res_test = []
for row in y_pred:
    ind = np.argmax(row)
    res_test.append(ind)
res_test = np.array(res_test)
print(res_test.shape)

(10000,)


In [109]:
print(y_test.shape)

(10000,)


In [110]:
confusion_matrix(y_test.reshape(-1, 1), res_test), accuracy_score(y_test.reshape(-1, 1), res_test)

(array([[ 968,    1,    1,    0,    0,    2,    4,    2,    2,    0],
        [   0, 1118,    3,    3,    1,    0,    1,    0,    9,    0],
        [   8,    3,  982,   14,    2,    0,    3,    9,   11,    0],
        [   1,    0,    3,  985,    0,    9,    0,    9,    2,    1],
        [   1,    0,    3,    0,  951,    0,    8,    3,    1,   15],
        [   3,    0,    0,   30,    1,  833,   16,    1,    6,    2],
        [   6,    3,    0,    0,    3,    6,  933,    0,    7,    0],
        [   3,    4,   13,   13,    2,    0,    0,  985,    0,    8],
        [   7,    0,    3,    9,    6,    8,    3,    3,  926,    9],
        [   3,    6,    2,    9,   22,    6,    1,    9,    5,  946]],
       dtype=int64),
 0.9627)

# Checking the change using CNN

In [261]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = x_train.reshape((-1, 28, 28, 1)) / 255
x_test = x_test.reshape((-1, 28, 28, 1)) / 255
print(x_train.shape)
enc = OneHotEncoder()
y_train = enc.fit_transform(y_train.reshape(-1, 1)).toarray()

(60000, 28, 28, 1)


In [262]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

model_cnn = Sequential()
model_cnn.add(Conv2D(filters=10, kernel_size=2, strides=1, padding="same"))
model_cnn.add(MaxPooling2D(pool_size=2, strides=1, padding="same"))
model_cnn.add(Conv2D(filters=10, kernel_size=2, strides=1, padding="same"))
model_cnn.add(MaxPooling2D(pool_size=4, strides=1, padding="same"))
model_cnn.add(Flatten())
model_cnn.add(Dense(32, activation="gelu"))
model_cnn.add(Dense(16, activation="gelu"))
model_cnn.add(Dense(10, activation="softmax"))
model_cnn.compile(optimizer="sgd", loss="categorical_crossentropy", metrics = ['accuracy'])

In [263]:
model_cnn.fit(x_train, y_train, epochs = 200, batch_size = 512)

Epoch 1/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - accuracy: 0.3321 - loss: 2.0386
Epoch 2/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - accuracy: 0.7835 - loss: 0.7279
Epoch 3/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - accuracy: 0.8652 - loss: 0.4544
Epoch 4/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - accuracy: 0.8880 - loss: 0.3745
Epoch 5/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - accuracy: 0.9034 - loss: 0.3216
Epoch 6/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9142 - loss: 0.2859
Epoch 7/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - accuracy: 0.9149 - loss: 0.2880
Epoch 8/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - accuracy: 0.9307 - loss: 0.2347
Epoch 9/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - accuracy: 0.9333 - loss: 0.2246
Epoch 10/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - accuracy: 0.9373 - loss: 0.2086
Epoch 11/200
118/118 ━━━━━━━━━━━━━━━━━━━━ 4s 32ms/step - accuracy: 0.9422 - loss: 0.1954
Epoch 12/200
118/118 ━━━━━━━━━

In [264]:
y_cnn = model_cnn.predict(x_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [265]:
res_cnn = []
for row in y_cnn:
    ind = np.argmax(row)
    res_cnn.append(ind)
res_cnn = np.array(res_cnn)
print(res_cnn.shape)

(10000,)


In [266]:
confusion_matrix(y_test.reshape(-1, 1), res_cnn), accuracy_score(y_test.reshape(-1, 1), res_cnn)

(array([[ 974,    0,    1,    0,    0,    0,    2,    1,    2,    0],
        [   0, 1129,    1,    2,    0,    1,    0,    2,    0,    0],
        [   2,    1, 1010,    4,    2,    0,    0,    4,    7,    2],
        [   0,    0,    1, 1003,    0,    4,    0,    1,    1,    0],
        [   0,    0,    1,    0,  976,    0,    0,    0,    0,    5],
        [   1,    0,    0,    3,    0,  884,    2,    0,    2,    0],
        [   4,    2,    1,    0,    3,    6,  939,    0,    3,    0],
        [   0,    0,    4,    1,    0,    0,    0, 1019,    1,    3],
        [   5,    0,    2,    5,    0,    2,    0,    2,  954,    4],
        [   1,    1,    0,    4,    4,    4,    0,    5,    3,  987]],
       dtype=int64),
 0.9875)